name: Validate PRs

on:
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
      - name: Run Biome
        run: biome ci .

  e2e:
    name: Run e2e tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-0 libgraphene-1.0-0 libwoff2dec1 libvpx9 libevent-2.1-7 libopus0 \
          libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 libgstaudio-1.0-0 libgstgl-1.0-0 \
          libgsttag-1.0-0 libgstvideo-1.0-0 libgstcodecparsers-1.0-0 libgstfft-1.0-0 flite1-dev \
          libavif16 libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 libgles2 x264
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
            frontend/.next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Install dependencies
        run: pnpm install && pnpm -filter database push && pnpm --filter database generate
        
      - name: Run Playwright tests
        run: pnpm --filter web e2e:ci
        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/apps/web/playwright-report/
          retention-days: 30
